// Unity Build generated by CMake
#include </projects/bengine-new/src/graphics/be_graphics_kernel.cpp>
#include </projects/bengine-new/src/graphics/be_texture.cpp>
#include </projects/bengine-new/src/graphics/be_framebuffer.cpp>
#include </projects/bengine-new/src/graphics/be_buffer.cpp>
#include </projects/bengine-new/src/graphics/be_vertex_array.cpp>
#include </projects/bengine-new/src/graphics/be_shader.cpp>
#include </projects/bengine-new/src/graphics/be_mesh.cpp>
#include </projects/bengine-new/src/graphics/be_graphics_system.cpp>
#include </projects/bengine-new/src/graphics/be_camera.cpp>
#include </projects/bengine-new/src/graphics/be_color.cpp>
#include </projects/bengine-new/src/graphics/sc_graphics.cpp>
